/* empty css                      */import{S as v,a as w,i as E}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const $="42580380-f7e9d56cf0d50abf8107b2707",I="https://pixabay.com/api/",P=document.getElementById("search-form"),m=document.getElementById("gallery"),B=document.getElementById("loader"),l=document.getElementById("load-more");let p,a=1,c="",f=0;P.addEventListener("submit",async e=>{if(e.preventDefault(),c=document.getElementById("query").value.trim(),c!==""){O(),u(!0),l.classList.add("hidden"),a=1;try{const r=await g(c,a),n=r.hits;if(f=r.totalHits,n.length===0){d("Sorry, there are no images matching your search query. Please try again!");return}y(n),p=new v("#gallery a"),n.length<f&&l.classList.remove("hidden")}catch(r){h(r)}finally{u(!1)}}});l.addEventListener("click",async()=>{a+=1,u(!0);try{const r=(await g(c,a)).hits;y(r),p.refresh(),S(),a*40>=f&&(l.classList.add("hidden"),d("We're sorry, but you've reached the end of search results."))}catch(e){h(e)}finally{u(!1)}});async function g(e,r){const n=`${I}?key=${$}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=40&page=${r}`;return(await w.get(n)).data}function h(e){e.response&&e.response.status!==200?d("There was a problem with the network connection. Please try again later."):d("An unexpected error occurred. Please try again.")}function d(e){E.error({title:"Error",message:e})}function y(e){const r=e.map(({webformatURL:n,largeImageURL:s,tags:t,likes:o,views:i,comments:L,downloads:b})=>`
        <div class="gallery-item">
          <a href="${s}">
            <img src="${n}" alt="${t}" />
          </a>
          <div class="info">
            <p>Likes: ${o}</p>
            <p>Views: ${i}</p>
            <p>Comments: ${L}</p>
            <p>Downloads: ${b}</p>
          </div>
        </div>`).join("");m.insertAdjacentHTML("beforeend",r)}function O(){m.innerHTML=""}function u(e){B.classList.toggle("hidden",!e)}function S(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
