/* empty css                      */import{S as I,a as P,i as O}from"./assets/vendor-Qob_5Ba8.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const B="42580380-f7e9d56cf0d50abf8107b2707",M="https://pixabay.com/api/";document.addEventListener("DOMContentLoaded",()=>{const u=document.getElementById("search-form"),i=document.getElementById("gallery"),c=document.getElementById("loader"),n=document.getElementById("load-more");if(!u||!i||!c||!n){console.error("One or more elements are missing in the DOM.");return}let e,t=1,s="",f=0;u.addEventListener("submit",async r=>{if(r.preventDefault(),s=document.getElementById("query").value.trim(),s!==""){y(),d(!0),n.classList.add("hidden"),t=1;try{const o=await m(s,t),a=o.hits;if(f=o.totalHits,a.length===0){l("Sorry, there are no images matching your search query. Please try again!");return}g(a),e=new I("#gallery a"),a.length<f&&n.classList.remove("hidden")}catch(o){p(o)}finally{d(!1)}}}),n.addEventListener("click",async()=>{t+=1,d(!0);try{const o=(await m(s,t)).hits;g(o),e.refresh(),L(),t*20>=f&&(n.classList.add("hidden"),l("We're sorry, but you've reached the end of search results."))}catch(r){p(r)}finally{d(!1)}});async function m(r,o){const a=`${M}?key=${B}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=20&page=${o}`;return(await P.get(a)).data}function p(r){r.response&&r.response.status!==200?l("There was a problem with the network connection. Please try again later."):l("An unexpected error occurred. Please try again.")}function l(r){O.error({title:"Error",message:r})}function g(r){const o=r.map(({webformatURL:a,largeImageURL:h,tags:v,likes:b,views:w,comments:E,downloads:$})=>`
          <div class="gallery-item">
            <a href="${h}">
              <img src="${a}" alt="${v}" />
            </a>
            <div class="info">
              <p>Likes: ${b}</p>
              <p>Views: ${w}</p>
              <p>Comments: ${E}</p>
              <p>Downloads: ${$}</p>
            </div>
          </div>`).join("");i.insertAdjacentHTML("beforeend",o)}function y(){i.innerHTML=""}function d(r){c&&c.classList.toggle("hidden",!r)}function L(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
